server:
  port: 8080

spring:
  application:
    name: modulix-admin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/modulix_admin?useSSL=false&serverTimezone=UTC
    username: root
    password: lipanre
sa-token:
  token-name: Authorization
  jwt-secret-key: "z0VND5TUVC9QhM68nrB8flll23IPgPTK"
  timeout: 6000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl